version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/distributedProject
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8081:8080"
    depends_on:
      - db


  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Fertare.2001
      MYSQL_DATABASE: distributedProject
      MYSQL_USER: root
      MYSQL_PASSWORD: Fertare.2001
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql


volumes:
  db-data:


